# Generated by Django 2.2.6 on 2019-10-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nan_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='genre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
